#!/usr/bin/env bash

genome=$1
echo "GENOME=$genome"

index_file="data/binaries/${genome}_k0.sa"

javac -d out/production/cmsc701 -cp src src/hw1/*.java

for QUERY in 10 50 100 200 500 1000 2000 10000 20000 50000; do
  for METHOD in naive simpaccel; do
    echo QUERY_LENGTH=$QUERY METHOD=$METHOD
    queries_file="data/queries/${genome}_queries_$QUERY.fa"
    out_file="data/outputs/${genome}_${QUERY}_${METHOD}.out"
    echo "${queries_file}" "${out_file}" $METHOD
    java -cp out/production/cmsc701 hw1.querysa "$index_file" "$queries_file" "$METHOD" "$out_file"
    echo -e "\n"
  done
done
