#!/usr/bin/env bash
#javac -d out/production/cmsc701 -cp src src/hw1/*.java
#java -cp out/production/cmsc701 hw1.querysa "$@"

genome=$1

for QUERY in 10 50 100 200 500 1000 2000 10000 20000 50000; do
  for METHOD in naive simpaccel; do
    echo K=$K QUERY_LENGTH=$QUERY METHOD=$METHOD
    javac -d out/production/cmsc701 -cp src src/hw1/*.java
    java -cp out/production/cmsc701 hw1.querysa "data/binaries/$genome.sa" "data/queries/$genome_queries_$QUERY.fa" "$METHOD" "data/outputs/$genome_$QUERY_$METHOD.out"
  done
done
